# Generated by Django 5.1.3 on 2024-11-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_id",
            new_name="id",
        ),
    ]
