# Generated by Django 5.1.3 on 2024-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_ingredient_options_alter_maincategory_options_and_more"),
        ("restaurant", "0002_alter_restaurant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincategory",
            name="restaurant",
            field=models.ManyToManyField(
                related_name="main_categories", to="restaurant.restaurant"
            ),
        ),
    ]
