# Generated by Django 5.1.3 on 2024-11-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
            },
        ),
        migrations.AlterModelOptions(
            name="maincategory",
            options={
                "verbose_name": "Main Category",
                "verbose_name_plural": "Main Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={"verbose_name": "Menu Item", "verbose_name_plural": "Menu Items"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
            },
        ),
    ]
