# Generated by Django 5.1.3 on 2024-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_maincategory_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="menu_item",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="menu_item",
            field=models.ManyToManyField(
                related_name="ingredients", to="menu.menuitem"
            ),
        ),
    ]
